name: Terraform Continuous Deployment

on:
  push:
    branches:
    - main

env:
  TERRAFORM_VERSION: 1.9.5

jobs:

  on-azure:
    name: Azure provider
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID      : ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET  : ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID      : ${{ secrets.ARM_TENANT_ID }}

    steps:

    - name: Step 01 - Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION

    - name: Step 02 - Terraform Version
      run : terraform --version

    - name: Step 03 - CheckOut GitHub Repo
      uses: actions/checkout@v4

    - name: Step 04 - Terraform Init
      run : terraform -chdir=./terraform/azure init

    - name: Step 05 - Terraform Validate
      run : terraform -chdir=./terraform/azure validate

    - name: Step 06 - Terraform Plan
      run : terraform -chdir=./terraform/azure plan -destroy -out tfplan

    - name: Step 07 - Terraform Apply
      run : terraform -chdir=./terraform/azure apply tfplan

    - name: Step 08 - Terraform Show
      run : terraform -chdir=./terraform/azure show